services:
  - type: web
    name: trainer-supply-backend
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 80
      - key: JWT_SECRET
        sync: false
      - key: MONGODB_URI
        sync: false
      - key: JWT_EXPIRE
        value: 7d
      - key: FRONTEND_URL
        value: https://trainer-supply-frontend.vercel.app
    healthCheckPath: /
    autoDeploy: true
