services:
  - type: web
    name: trainer-supply-backend
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 80
      - key: JWT_SECRET
        sync: false
      - key: MONGODB_URI
        sync: false
    healthCheckPath: /
    autoDeploy: true
